### ISSUE TITLE
The rule for detecting unicode or zawgyi has problem

### ISSUE THREAD

**Issue by rodent129** [septemberboy7/MDetect#1]
I tested with your library. My device use the zawgyi font. But when call the MDetect.isUnicode(), it is return true, so the font are not correctly showed.

**Comment by dev-myatminsoe** [comment]
What's your device and can you send me the font(ttf) that you are using?

**Comment by rodent129** [comment]
ASUS zenfone and i think i downloaed the zawgyi samsung font.

**Comment by rodent129** [comment]
After tracing, i found that i change the display font style to zawgyi samsung. May be that's why it can't detect...
