### ISSUE TITLE
Ask for detecting income string

### ISSUE THREAD

**Issue by moejnr** [septemberboy7/MDetect#4]
Any way to detect the incoming string from server is Unicode or Zawgyi? Without using MMTextView. I need to check like this.
if (!MDetect.INSTANCE.isUnicode()) {
            // Here the incoming string is Zawgyi and device supported is Zawgyi, no need to convert by Rabbit converter
            textView.setText(string);
        } else {
            // Here the incoming string is Unicode and device supported is Zawgyi, i need to convert by Rabbit converter
            textView.setText(Rabbit.uni2zg(string));
        }
Could you tell me the way to solve it?

**Comment by dev-myatminsoe** [comment]
There is no 100% correct method for detecting the string. For e.g. "ပြ" (\u1015\u103C) is 'pya' in Unicode and 'pwa' in Zawgyi. Both are legitimate. But there's a regex if you need one.

[](https://github.com/Rabbit-Converter/Rabbit/issues/10)
